#!/usr/bin/python3
from sys import argv

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def factorize(num):
    if num % 2 == 0:
        return num // 2, 2

    for i in range(3, num, 2):
        if num % i == 0 and is_prime(i):
            factor = num // i
            for j in range(3, factor, 2):
                if factor % j == 0 or i % j == 0:
                    break
            else:
                return factor, i

    return None, None

def main():
    if len(argv) != 2:
        print("Usage: {} <file>".format(argv[0]))
        exit(1)

    filename = argv[1]

    with open(filename) as f:
        for line in f:
            num = int(line.strip())
            p, q = factorize(num)
            if p is not None:
                print("{}={}*{}".format(num, p, q))

if __name__ == "__main__":
    main()
